name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t akila1908/healthcarejenkinsapp:latest .
          docker push akila1908/healthcarejenkinsapp:latest

      - name: Setup SSH and Pull Docker Image on EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull Docker Image on EC2
        run: |
            ssh -o StrictHostKeyChecking=no "${{ secrets.EC2_USERNAME }}"@${{ secrets.EC2_HOST }} 'docker login -u akila1908 -p "${{ secrets.DOCKERHUB_TOKEN }}" && docker pull akila1908/healthcarejenkinsapp:latest'

      - name: Run Docker Container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.EC2_USERNAME }}"@${{ secrets.EC2_HOST }} 'docker stop my-container || true && docker rm my-container || true && docker run -d -p 80:80 --name my-container akila1908/healthcarejenkinsapp:latest'
